### ISSUE TITLE
Cannot compile files with spaces in their paths

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#1471]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

I tried compiling a file with a space in its path

### I expected this:

The compile to succeed

### Instead, this happened:

Error

### Component:

Compiler

### Wing Version:

0.5.11

### Node.js Version:

18.12.1

### Platform(s):

MacOS

**Comment by Chriscbr** [comment]
Great catch @ShaiBer

**Comment by staycoolcall911** [comment]
Should be easy to look into this [here](https://github.com/winglang/wing/blob/f8467b5a83f4b8ad904aa942f0e2bc701df9177f/apps/wing/src/commands/compile.ts#L63). We should see if this bug applies also to the `run` and `test` commands and perhaps the solution should be in the [`util.ts:normalPath` function](https://github.com/winglang/wing/blob/f8467b5a83f4b8ad904aa942f0e2bc701df9177f/apps/wing/src/util.ts#L4).

**Comment by msalman-abid** [comment]
@ShaiBer The command works fine when the whitespace is escaped i.e. `wing compile a\ b.w -t tf-aws`. Is this not intended behaviour?

**Comment by ShaiBer** [comment]
> @ShaiBer The command works fine when the whitespace is escaped i.e. `wing compile a\ b.w -t tf-aws`. Is this not intended behaviour?

Cool, I didn't know that the escape works, but I would still expect it to work without it, or at least with surrounding the path with quotes.
In any case, we need a better error when someone fails to use the escape so they understand that the problem was the space.

**Comment by MarkMcCulloh** [comment]
I'm not sure any change is needed here. Spaces require escaping/quotes in most CLI usage. I suppose right now it's possible to fix because we only accept 1 positional argument so can intentionally try to combine any extras, but AFAIK this is not really something expected from CLI programs. And if/when we accept multiple args this would not be feasible.

The current error you would get from Wing is `Source file cannot be found: <file>`, I feel like that should be enough indication to users that their input was malformed.

**Comment by ShaiBer** [comment]
I guess you're right, but since it has happened more than once to more than one person then maybe we can just add a hint to the error saying to make sure you don't have unescaped spaces?

**Comment by WeepingClown13** [comment]
Since this is not an uncommon scenario, how about adding the details to the getting started guide rather than the error message? I mean, from a user perspective it's quite obvious that you don't exactly leave spaces as is when using the command line. Occasional mishaps may happen but as @MarkMcCulloh mentioned the current error message is quite sufficient as you can notice the incomplete filename there. So maybe add something like "make sure to escape the spaces or quote the path if the path contains spaces" to the wing compile section in getting started? Maybe not the perfect solution but this is not exactly a new thing or an issue to begin with.
