### ISSUE TITLE
Differentiate files and directories when listing bucket contents

### ISSUE THREAD

**Issue by polamoros** [winglang/wing#1673]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### Feature Spec

`bucket.list` returns information about each file/dir inside a bucket.

```
const response = await bucket.list();

[
  {
    name: "a",
    type: "directory",
    size: "196", // bytes
    last_modified: "1057984701"
  },
  {
    name: "hello.txt",
    type: "file",
    size: "12", // bytes
    last_modified: "1057984701"
  }
]
```

`bucket.list` has an option to retrieve files in a specific path.

```
const response = await bucket.list(undefined, 'a');

[
  {
    name: "hello_inside_a.txt",
    type: "file",
    size: "12", // bytes
    last_modified: "1057984701"
  }
]
```

### Use Cases

As a Console user, I would like to be able to see files and directories inside buckets.

<img width="184" alt="image" src="https://user-images.githubusercontent.com/5547636/221523671-7d3a76eb-8dc0-4b9a-94a3-d13a66ffb56b.png">

<img width="676" alt="image" src="https://user-images.githubusercontent.com/5547636/221523741-d03de3c4-99f8-40d7-a98d-01cd62374558.png">

### Component

SDK

**Comment by skyrpex** [comment]
I'd propose using an options object for the list method:

```ts
const response = await bucket.list({ prefix: "my_prefix", path: "my_dir/" });
```

**Comment by Chriscbr** [comment]
So, the interesting thing here is that technically `cloud.Bucket` only provides an abstraction for files. That is, you cannot create or delete directories on AWS S3 or Azure Blob Storage etc. This is because at the underlying hardware level, they are not storing your objects using a file system, but simply as a distributed key-value store  -- the fact that most keys resemble file paths is just convention. 😅 

*However*, as you've noted, we do want to provide this illusion of being able browse objects as if it were a file system. Since this use case is so common, the way AWS and Azure APIs support this (and how I understand their web consoles work under the hood) is they offer a "delimiter" option in their API. The way it works is like this:

Given these files:
```
pictures/January/photo1.png
pictures/January/photo2.png
pictures/February/photo1.png
pictures/February/photo2.png
```

Then you can call the List API on AWS with `prefix: "pictures/", delimiter: "/"` to obtain a list of pseudo-folders inside `pictures`:

```
pictures/January/
pictures/February/
```

My proposal would be:
1. Add the `delimiter` option to `bucket.list()` (for users that have already used AWS/Azure/etc and expect this)
2. Add a `bucket.list_folders()` API which is just an alias for calling `bucket.list()` with the `delimiter` option

Thoughts?

**Comment by eladb** [comment]
I don't think we really need dedicated API for directories. I think all object stores don't model directories explicitly, just by treating the delimited prefix of the object as a path.

The `list()` API has a prefix which allows clients to query only files within a certain subtree of the key space.

Not sure an illusion of a file structure is something we need to model in the SDK.

**Comment by polamoros** [comment]
Using the prefix to "simulate" directories in the Console is more than fine.

The thing is, If I try to do `bucket.put('pictures/January/photo1.png', content)`, I get an error because the simulator is trying to create the file inside the specified path that doesn't exist.

<img width="921" alt="image" src="https://user-images.githubusercontent.com/5547636/221806582-898fe772-46b7-4b6e-b95e-0321a3271e47.png">

What should we do in this case?

**Comment by polamoros** [comment]
> Using the prefix to "simulate" directories in the Console is more than fine.
> 
> The thing is, If I try to do `bucket.put('pictures/January/photo1.png', content)`, I get an error because the simulator is trying to create the file inside the specified path that doesn't exist.
> 
> <img alt="image" width="921" src="https://user-images.githubusercontent.com/5547636/221806582-898fe772-46b7-4b6e-b95e-0321a3271e47.png">
> 
> What should we do in this case?

I just saw [this]( https://github.com/winglang/wing/issues/1674#issuecomment-1447614612) 👍

**Comment by skyrpex** [comment]
@Chriscbr oh, that's a clever use of the prefix! I like it, and agree with your `delimiter` proposal. I don't think we need a `list_folders()` sugar method.
