### ISSUE TITLE
Can we deprecate `WING_TARGET`?

### ISSUE THREAD

**Issue by eladb** [winglang/wing#2077]
Random thought: Why do we put `process.env.WING_TARGET` here? Isn't the compiler artifact expected to be target specific? 
wingc knows the target so it could explicitly put it here.

_Originally posted by @MarkMcCulloh in https://github.com/winglang/wing/pull/2076#discussion_r1166794026_

**Comment by Chriscbr** [comment]
It could be nice to get to a place where you can reproduce/debug a preflight file by running `node path/to/preflight.js` without having to set tons of environment variables -- today it's not possible because the CLI injects many custom global variables:

https://github.com/winglang/wing/blob/12580add341b7dfc84c3c961a643104a948c7c0a/apps/wing/src/commands/compile.ts#L191-L210

**Comment by eladb** [comment]
I think we are using `WING_TARGET` now for realz. Closing.
