### ISSUE TITLE
Automating the compatibility matrix update

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#2396]
### Feature Spec

Right now updating the compatibility matrix is done manually- we are planning to add it to the build as a next step :)

It's not so straightforward- 
- even if someone adds a resource/ method to the resource, we can't know if it's a working one, or a non-implemented-yet error unless we run it, 
and if we run it automatically we can get errors for calling the method with "wrong" arguments (and then this error might be configured in the father class) so we can never know it is implemented for real unless we'll ask the developer- 

- We can potentially ask the developer in the terminal, but then for each build, they'll have to go through a few questions and should notice them to be able to type "y" or "n" (like sometimes we forget to type "yes" to terraform apply and come back 10 minutes later, and nothing was done), 
 
- we should think of a more sophisticated way...

### Use Cases

contributor experience, and the integrity of the matrix

### Component

SDK, Documentation

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by garysassano** [comment]
One way to automate the process could be that only classes/methods that have existing tests and that pass all the tests would be added automatically to the matrix. This of course would imply that Wing reached a quite mature state where all the tests got populated, so something more for the future.

**Comment by garysassano** [comment]
I agree with @ekeren. In order for a class/method to be added to the matrix automatically, it should have related tests that have 100% coverage.  If there are tests that are WIP, we could introduce a special keyword that you specify at the beginning of the file that tells the process to ignore that test even if passes.

**Comment by garysassano** [comment]
I agree with @ekeren. In order for a class/method to be added to the matrix automatically, it should have related tests that have 100% coverage.  If there are tests that are WIP, we could introduce a special keyword that you specify at the beginning of the file that tells the process to ignore that test even if it passes.

**Comment by Chriscbr** [comment]
Idea: generate the matrix based on the JSII metadata (.jsii file) produced by the SDK. This is a big JSON file that lists all of the APIs in the SDK. For each resource, a script would check the resource's API in the `cloud` namespace to see what properties and methods are supported, and then find all classes that extend that class for the other targets (like `sim`, `tf-aws`, and so on), and track what APIs they implement.

In order to satisfy abstract classes, the SDK sometimes implements stub methods like shown here:
https://github.com/winglang/wing/blob/7b8f46649ae19cc81dd7d0ee34e21d0737b0e79e/libs/wingsdk/src/target-tf-azure/bucket.ts#L166-L175

In order to avoid showing those methods as supported, if we add a tag to the docstring like "@unimplemented" then the the .jsii file will include the tag and our script can add a more correct answer. We even extend this to have links to the issues in our source code, like `@unimplemented https://github.com/winglang/wing/issues/1954`.

caveats: this approach wouldn't look at tests, and it also would only work if we export all namespaces [here](https://github.com/winglang/wing/blob/main/libs/wingsdk/src/index.ts)

**Comment by ekeren** [comment]
Keep (FYI @tsuf239 )
