### ISSUE TITLE
Add tab view in Playground/Tutorial to show either the simulator map view or lists of generated resources in the different clouds

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2495]
### Feature Spec

Users are now better able to understand that Wing is not a toy when playing in the playground or doing a tutorial because they see in a clear way that we generate real cloud code

### Use Cases

To show users we are not a toy. The simulator compiles so fast, users might not understand this is real cloud code

### Implementation Notes

@eladb has thoughts on exactly what this should look like

### Component

Playground, Tutorial

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
Here is a sketch of how this could look like

![Image](https://github.com/winglang/wing/assets/1727147/d5859d12-3e36-42b6-aab9-1cf5e8e0b7f8)

**Comment by ShaiBer** [comment]
I love the direction, just missing a way to download the artifacts

**Comment by ekeren** [comment]
Added a way to download the artifacts 

![out](https://github.com/winglang/wing/assets/1727147/04aedb79-70ad-4fa8-8980-54c9d4ceef8d)

**Comment by ainvoner** [comment]
https://www.convertsimple.com/convert-json-to-hcl/

**Comment by ainvoner** [comment]
let's start by supporting the following:
1. design a new "target output" view by target type (we can use the design in the above comment or suggest a new one)
2. each step can define what to display in the target output section - simulator, aws/terraform, etc... there can be more than one target output. in case of multiple target outputs, we can use tabs (as in the above design).
3. start with implementing AWS/Terraform target output
4. compile to the simulator target is done automatically by the console
5. compile to any other targets is done by clicking a "Compile" button

example:
1. step 1 has a AWS/Terraform target output. The user in this step will see a view like in https://github.com/winglang/wing/issues/2495#issuecomment-1546893954 
2. step 2 has a Simulator target output. The user in this step will see the console (as it is now in lean.winglang.io)
3. final step has as array of target outputs [AWS/TF, Simulator]. The user will see each output view in a different tab (as shown above)

**Comment by ekeren** [comment]
@ainvoner , Maybe I should build something like this [v1 Tour](https://docs.google.com/presentation/d/1QmJ93w_fiFhbRxdhGeMPBZio-Ktt-Fn0j88RpyPhLCY/edit#slide=id.g23df20440a8_0_4) for my desired  new flow?

**Comment by ekeren** [comment]
>  this site https://www.convertsimple.com/convert-json-to-hcl/ uses https://github.com/vgsantoniazzi/js-hcl-parser which I think enough for our needs



@skorfmann will help us with the "right" way to convert json->HCL 

I showed him https://www.convertsimple.com/convert-json-to-hcl/  and he didn't approve

**Comment by polamoros** [comment]
AWS resource icons [link](https://d1.awsstatic.com/webteam/architecture-icons/q2-2023/Asset-Package_04282023.ca9655a386a46bda0b6238cca2651e8f27fcb5c9.zip)

**Comment by skorfmann** [comment]
> @skorfmann will help us with the "right" way to convert json->HCL
> I showed him https://www.convertsimple.com/convert-json-to-hcl/ and he didn't approve

Yes, the syntax which is produced by these tools is neither idiomatic nor functional Terraform HCL config, but looks like some weird JSON like syntax (maybe HCL v1?). I think the challenge is, that the default use case is going from HCL to JSON for machine readable formats. The other way around is super rare. See this issue from the lib that’s being used in cdktf for hcl2json tasks https://github.com/tmccombs/hcl2json/issues/2 - Plus, there's another issue in cdktf essentially requesting the same thing: https://github.com/hashicorp/terraform-cdk/issues/225. TL;DR: HCL is a toolkit to build languages where Terraform HCL is a specific implementation of it. Converting from HCL -> JSON is straightforward, going reverse needs type information from the Terraform provider in some cases.

So, let's take a wing generated Lambda function as an example, the converted JSON from this tool looks like this:

```hcl
"aws_lambda_function" "root_env0_cloudQueueAddConsumer3915c5ec_D9C8326B" {
  "//" "metadata" {
    "path" = "root/Default/env0/cloud.Queue-AddConsumer-3915c5ec/Default"

    "uniqueId" = "root_env0_cloudQueueAddConsumer3915c5ec_D9C8326B"
  }

  "environment" "variables" {
    "BUCKET_NAME_90d3f186" = "${aws_s3_bucket.root_env0_cloudBucket_DA9B7293.bucket}"

    "BUCKET_NAME_90d3f186_IS_PUBLIC" = "false"

    "WING_FUNCTION_NAME" = "cloud-Queue-AddConsumer-3915c5ec-c83da7e5"
  }

  "function_name" = "cloud-Queue-AddConsumer-3915c5ec-c83da7e5"

  "handler" = "index.handler"

  "publish" = true

  "role" = "${aws_iam_role.root_env0_cloudQueueAddConsumer3915c5ec_IamRole_54033248.arn}"

  "runtime" = "nodejs18.x"

  "s3_bucket" = "${aws_s3_bucket.root_Code_02F3C603.bucket}"

  "s3_key" = "${aws_s3_object.root_env0_cloudQueueAddConsumer3915c5ec_S3Object_F86765F2.key}"

  "timeout" = 30

  "vpc_config" = {
    "security_group_ids" = []

    "subnet_ids" = []
  }
```

vs the one you’d actually want to have

```
resource "aws_lambda_function" "root_env0_cloudQueueAddConsumer3915c5ec_D9C8326B" {
  function_name = "cloud-Queue-AddConsumer-3915c5ec-c83da7e5"
  handler       = "index.handler"
  runtime       = "nodejs18.x"
  timeout       = 30
  publish       = true

  role = aws_iam_role.root_env0_cloudQueueAddConsumer3915c5ec_IamRole_54033248.arn
  s3_bucket = aws_s3_bucket.root_Code_02F3C603.bucket
  s3_key = aws_s3_object.root_env0_cloudQueueAddConsumer3915c5ec_S3Object_F86765F2.key

  vpc_config {
    security_group_ids = []
    subnet_ids = []
  }

  environment {
    variables = {
      BUCKET_NAME_90d3f186 = aws_s3_bucket.root_env0_cloudBucket_DA9B7293.bucket
      BUCKET_NAME_90d3f186_IS_PUBLIC = "false"
      WING_FUNCTION_NAME = "cloud-Queue-AddConsumer-3915c5ec-c83da7e5"
    }
  }
}
```

As you can see, it’s not too far off in terms of general structure. (compare the tf resource as well https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function)

One way could be to do some postprocessing. There are a few things that would need to be done:

- prepend `resource`
- get rid of `"` in keys
- no interpolation for references (e.g. the `s3_bucket` value)
- Drop `//` keys (comments in Terraform JSON)

The difficult part can be seen here:

```
  environment {
    variables = {
      BUCKET_NAME_90d3f186 = aws_s3_bucket.root_env0_cloudBucket_DA9B7293.bucket
      BUCKET_NAME_90d3f186_IS_PUBLIC = "false"
      WING_FUNCTION_NAME = "cloud-Queue-AddConsumer-3915c5ec-c83da7e5"
    }
  }
```

which looks like this in JSON

```
        "environment": {
          "variables": {
            "BUCKET_NAME_90d3f186": "${aws_s3_bucket.root_env0_cloudBucket_DA9B7293.bucket}",
            "BUCKET_NAME_90d3f186_IS_PUBLIC": "false",
            "WING_FUNCTION_NAME": "cloud-Queue-AddConsumer-3915c5ec-c83da7e5"
          }
        },
```

`environment` is a [block](https://developer.hashicorp.com/terraform/language/syntax/configuration#blocks), where `variables` is a `map` in tf hcl. So that’s impossible to know in a generic way by just looking at the JSON. Not sure how the converter guessed this, probably some heuristic. I think Terraform knows this by looking at the schema of the povider resource.

Another way could be, to actually build a dedicated TF JSON -> Terrform HCL converter. Here's an [example](https://www.reddit.com/r/Terraform/comments/1205az0/comment/jeum9ev/?utm_source=reddit&utm_medium=web2x&context=3) to do this for Terraform `tfvars` (which is a pretty simple case). 

Probably depends on how important this really is in the end.

**Comment by ekeren** [comment]
Done
