### ISSUE TITLE
Show the contents of a Queue in the Console

### ISSUE THREAD

**Issue by ShaiBer** [winglang/wing#2517]
### Feature Spec

Users are now able to see the contents of the queue in the Wing Console for easy debugging

### Use Cases

User pushes an item to the queue and naturally wants to see it there

### Implementation Notes

This is problematic since it's an API that does't exist in the actual clouds.
But I think we should be able to have console only APIs for debugging

### Component

Wing Console, Playground, Tutorial

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skorfmann** [comment]
Seeing these in the logs would already help quite a bit. When trying the getting started example, I originally thought it was broken, since there was no visual feedback at all 

- the text box wasn't reset (still had the text I put in) after clicking "send"
- no logs were there 

Only after finding the file in the bucket, I was able to confirm that it apparently worked.

**Comment by skorfmann** [comment]
Heh, right after sending this comment I discovered the log level filter :D - Perhaps considering a different log level would be helpful?

**Comment by ShaiBer** [comment]
Regardless of logs, I think it makes sense to be able to peek in the queue and see what's there in the simulator for debugging purposes, even if it's not something that is possible on the real cloud.
We also want to be able to put a break point on a queue, which is not possible in the real cloud.

**Comment by ainvoner** [comment]
duplication of [#1590](https://github.com/winglang/wing/issues/1590)
