### ISSUE TITLE
Deprecation warning in `jsii compile`

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#2533]
### I tried this:

``` 
cd libs/wingsdk
npm run build
```

### This happened:

Node 19 is approaching end-of-life and will no longer be supported in new releases after 2023-06-01- 
<img width="844" alt="image" src="https://github.com/winglang/wing/assets/39455181/f205e3db-9536-45aa-858c-201839f8a9f6">

### I expected this:

n/a

### Component

SDK

### Node.js Version

19.7.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
I think this error is based on the local version of node installed in your environment (not set up automatically), if you use Node v18 it should still be possible to build everything in the repo

**Comment by staycoolcall911** [comment]
Discussed this offline with @Chriscbr. NodeJS is not supporting version 19 as much as they do 18 ([reference](https://github.com/nodejs/release#release-schedule)). We will probably switch our CI/CD to work with node 18 & 20 instead of 18 & 19 at some point. 
In light of this, we shouldn't worry about jsii's support of node19. Closing this issue.
