### ISSUE TITLE
see inflight methods relations between resources 

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#2629]
### Feature Spec

calling an inflight method of a resource from another resource should have a visual representation in the console.
for example:

### Use Cases

```
class GitHub {
    inflight listIssues() {
    }
}

class Example {
  gh: GitHub;
  
  inflight report() {
      this.gh.listIssues();
  }
}
```
calling GitHub listIssues inflight method from the Example class will result a connection between those classes in the Console map.

### Implementation Notes

the bindings used by the compiler can be used to add this info to the sim target output json.

### Component

SDK, Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
@chrichts @ekeren  can you please add your insights about this issue.
I believe @Chriscbr will be able to add a more detailed and accurate implementation note.

**Comment by Chriscbr** [comment]
I was thinking about this issue for a bit and I think there might be some challenges fitting this into our current data model. I'll share some context and ideas:

----

Recall that an inflight method is only executed when it is called inside an inflight host (`cloud.Function`, `cloud.Service`, etc). Today, all the compiler + SDK work together to produce is a collection of facts with this "shape":

* Inflight host [A] uses operation [B] on object [C]

A, B, and C are variables that can substituted with different values. Today, A and C must be **instances of classes in the construct tree**, and B must be a **name of a method or field**. It collects these facts, and then uses them to "bind" each resource to each inflight host that uses it. For example, when an `cloud.Function` calls `publish` on a `cloud.Topic`, it creates a fact:

* Inflight host [root/MyTest] uses operation [publish] on object [root/cloud.Topic]

> Note that root/MyTest and root/cloud.Topic are paths to specific instances of classes in the construct tree.

The reason we structure facts like this is because it is the minimal information needed for the SDK to "bind" resources together. For example, based on this fact, the sdk calls `topic._bind(host, ["publish"])` which adds an environment variable to `host` with the physical resource name of the topic (e.g. an [AWS ARN](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference-arns.html)), and adds any required IAM permissions to the `host` needed for calling the "publish" on the topic. The `_bind` method has a different implementation for each cloud target.

We can see how this works with the example you gave:

```js
bring cloud;

class GitHub {
  inflight listIssues() {
  }
}

class Example {
  gh: GitHub;

  init() {
    this.gh = new GitHub();
  }

  inflight report() {
    this.gh.listIssues();
  }
}

let ex = new Example();

new cloud.Function(inflight () => {
  ex.report();
});
```

Based on this code, the compiler and SDK produce these two facts:

* Inflight host [root/cloud.Function] uses operation [report] on object [root/Example]
* Inflight host [root/cloud.Function] uses operation [listIssues] on object [root/GitHub]

These facts are translated into a form in JSON that the Wing Console can consume, and today produces a diagram like so:

<img width="512" alt="Screenshot 2023-05-23 at 4 07 17 PM" src="https://github.com/winglang/wing/assets/5008987/2c350571-f227-448b-87d6-788130c83372">

----

I think the issue is the information we want doesn't fit into this fact shape. We want to show how calling method A on class B results in calling method C on class D. (If this paragraph doesn't sound correct or is missing something, please add your thoughts in a comment before continuing reading 🙂).

One idea to solve this is to tweak our existing code so we produce facts like this:

* Inflight host [A] uses operation [B] on object [C] (via operation [D] on object [E])

The part in parentheses is extra metadata. In our earlier example, we would produce:

* Inflight host [root/cloud.Function] uses operation [report] on object [root/Example]
* Inflight host [root/cloud.Function] uses operation [listIssues] on object [root/GitHub] via operation [report] on object [root/Example]

This might work, though it seems a little bit clunky / it seems like there is redundant information. 🤔

Another idea is to tweak our code so that we produce two kinds of facts:

* **host fact** - inflight host [A] uses operation [B] on object [C]
* **class fact** - using operation [D] on object [E] uses operation [F] on object [G]

(Sorry for all of the variables 🙈)

In our earlier example, we would produce:

* Inflight host [root/cloud.Function] uses operation [report] on object [root/Example]
* Using operation [report] on object [root/Example] uses operation [listIssues] on object [root/GitHub]

I think this might be a more robust model. For the console, we would collect all of these facts together and expose them in tree.json like we do today, or some new file, whatever is easier (implementation detail). Using this information, it should be possible for the console team to render relationships between `Example` and `GitHub` in the previous example. In the SDK, we would have to tweak the logic in some places to pass additional information in order to produce the new facts.

note: **this would only show information about methods used in the application**. This means if a method like `report` is never called, then the host fact would not be generated, and possibly the class fact might not be generated either.

Thoughts?

**Comment by ekeren** [comment]
The last model seem to make sense to most to me, one note:

> Inflight host [root/cloud.Function] uses operation [report] on object [root/Example]
    Using operation [report] on object [root/Example] uses operation [listIssues] on object [root/GitHub]

The mental model I have in my mind for this is more of:
```
root/cloud.Function:handler -> root/Example:report 
root/Example:report -> root/GitHub:listIssues
```

**Comment by Chriscbr** [comment]
Keep. Cristian created some illustrative examples of the issue here: https://github.com/winglang/console-map-issues and I sketched out some ways we can emit better map information from the SDK in this PR: https://github.com/winglang/wing/pull/5869

**Comment by skyrpex** [comment]
This is the WIP for the Console map https://github.com/winglang/wing/pull/6243.

**Comment by skyrpex** [comment]
As far as I understand, the simulator already provides the necessary information and the console already displays it:

```wing
class GitHub {
    pub inflight listIssues() {
    }
}

class Example {
  gh: GitHub;

  new(gh: GitHub) {
    this.gh = gh;
  }
  
  inflight report() {
      this.gh.listIssues();
  }
}

new Example(new GitHub());
```

Shows as:

<img width="510" alt="image" src="https://github.com/user-attachments/assets/03875a3d-9346-4634-b5b1-67ae6a5de263">
