### ISSUE TITLE
Contributor experience: quick build+tests on a Windows machine to test and fix Windows related issues faster

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#2645]
### Feature Spec

As a contributor, I would like to have the option to run my build on a Windows machine solely, for faster feedback loops related to Windows errors.

### Use Cases

Sometimes the build and tests succeed on Linux and Mac, but fail on Windows. A common error is that we forget to normalize path strings.
See [this example](https://github.com/winglang/wing/actions/runs/5077675549/jobs/9121654237).
In these cases we usually follow up with a fix PR, but it takes a long time to see if the fix worked, since it has to build again on all environments (Linux, Mac, Node 18/19 etc.).
Instead, we'd like to run the fix PR only on Windows to see if our fix worked.

### Implementation Notes

Perhaps we can add a label, similar to `pr/e2e-full`, named `pr/e2e-windows`. When this label is added to a PR, the build would only run on Windows. 
After the build succeeds, we need a way to re-run our fix in the normal path, so it will get tested, merged to main and later published like every other PR.

### Component

Contributor Experience

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skorfmann** [comment]
Only tangentially related: Used this when reproducing issues around Windows for cdktf https://github.com/skorfmann/windows-test-machine - Haven't tried it in a while, but might still be helpful.

**Comment by WeepingClown13** [comment]
Thoughts after having some discussions with @staycoolcall911 and @MarkMcCulloh:
Since matrix parallel runs are not limited, all the tests run in parallel and hence the current method is already the fastest method there is. Even if we push windows to be the first in the matrix or run it alone, not only does the speed not increase, and at worst the complexity of the workflow also increases, which is counterproductive. Rather than looking at this bit, a better solution would be probably a complete rewrite of the current workflow.

**Comment by staycoolcall911** [comment]
Closing this for now as it doesn't seem to be an actionable pain (or a pain) any more.
