### ISSUE TITLE
cloud.Schedule init with both rate and cron should throw an exception

### ISSUE THREAD

**Issue by tsuf239** [winglang/wing#2732]
### I tried this:
test this on sim:

```
bring cloud;

try {
    new cloud.Schedule( rate: 2m, cron: "* * * * *" ) as "s2";
} catch e {
}
```

### This happened:

<img width="910" alt="image" src="https://github.com/winglang/wing/assets/39455181/e17e79eb-a82a-4d10-a4e6-739d346cbac0">
Validation error, cannot resolve alias "und"

### I expected this:

To run with no error/ showing a more appropriate error

### Component

Compiler, SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
I think this should fail, no? It doesn't make sense to have both rate and cron for Schedule.
It should fail in a nicer way, but this is p3.

**Comment by tsuf239** [comment]
It shouldn’t since it’s inside a try/catch scope
If I just put it in the wild it fails with the right error :)

בתאריך יום ה׳, 1 ביוני 2023 ב-10:03 מאת Uri Bar ***@***.***>:

**Comment by staycoolcall911** [comment]
Ok, I see what you mean now, thanks. I guess we don't really throw an exception in such cases. Wondering if we should propagate the exception in these cases. @Chriscbr - WDYT?

**Comment by tsuf239** [comment]
> Ok, I see what you mean now, thanks. I guess we don't really throw an exception in such cases. Wondering if we should propagate the exception in these cases. @Chriscbr - WDYT?

It compiles and works perfectly in aws.... (just creating nothing), I guess it should have the same result on the sim, it seems to be more of a compiler error than an SDK one

**Comment by Chriscbr** [comment]
This is pretty interesting @tsuf239, I haven't seen this come up before. It looks like `try/catch` shows how classes in Wing don't behave quite the same as classes in JavaScript or other object-oriented languages.

The issue is I'm not sure if the constructs programming model supports the notion of catching errors thrown during initialization. For example, if I have Wing code like this:

```js
class A {
  x: num;
  init(opt: bool) {
    if opt == true {
      throw("not allowed");
    }
    this.x = 5;
  }
}

try {
  new A(true);
} catch e {
  new A(false);
}

// ... more code
```

If `A` throws an error during initialization, the object ends up in a limbo state (not everything may be initialized). You might imagine that maybe that means the object will not get created, so if you use `try / catch` you can simply ignore the error and try creating a different object, like I did in the example above.

But because we are using constructs, A will be created in your construct "tree" before initialization has finished, causing `new A(false)` to fail.

Here's the code in plain JavaScript that also shows the issue:

```js
const constructs = require("constructs");

// the "root" or "app" is implicit in Wing, but every construct tree has one
class App extends constructs.Construct {
  constructor() { super(undefined, ""); }
}

class A extends constructs.Construct {
  constructor(scope, id, opt) {
    super(scope, id);
    if (opt === true) {
      throw new Error("not allowed");
    }
    this.x = 5;
  }
}

let app = new App();
try {
  new A(app, "Test", true);
} catch (e) {
  new A(app, "Test", false);
}
```

It throws an error "Error: There is already a Construct with name 'Test' in App". This happens because `A` is added to the tree during `super`, not at the end of initialization.

This is a kind of a limitation of the constructs programming model. (You also can't delete constructs after they have been added to a construct tree). I'm not sure what the best solution is for this, but maybe there is some way we can make this behavior less surprising to users?

**Comment by yoav-steinberg** [comment]
eek, that's kind of ugly. We can perhaps disable any `new` expressions inside a try-catch block?

**Comment by tsuf239** [comment]
> eek, that's kind of ugly. We can perhaps disable any `new` expressions inside a try-catch block?

The code is compiling and executing on tf-aws somehow, so disabling will "hurt" this functionality, maybe it's better to keep it as a known issue... what difference between aws to the sim does lead to this change in behavior?

**Comment by ekeren** [comment]
I think that the right API for this use case is making the Schedule constructor private and giving 2 factory methods instead

```ts (wing)
let s1 = cloud.Schedule.fromCron(...);
let s2 = cloud.Schedule.fromRate(...);
```

**Comment by ekeren** [comment]
I think that our language doesn't support this model, right @yoav-steinberg ? 

> I think that the right API for this use case is making the Schedule constructor private and giving 2 factory methods instead
> 
> ```ts
> let s1 = cloud.Schedule.fromCron(...);
> let s2 = cloud.Schedule.fromRate(...);
> ```

**Comment by Chriscbr** [comment]
Let's continue any discussion about try/catch in this new issue: https://github.com/winglang/wing/issues/3544

**Comment by staycoolcall911** [comment]
The main issue is described in #3544 - I think we can close this.
