### ISSUE TITLE
Rename `Json` to `ImmutableJson` and `MutJson` to `MutableJson`

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#2777]
### Feature Spec

I think that `Json` should follow the same convention as `Array`, `Map` and `Set` within the [API Reference](https://github.com/winglang/wing/blob/main/docs/05-reference/wingsdk-api.md).

### Use Cases

Standardize naming convention for types in Wing.

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
Thanks @garysassano, but it's actually the other way around - we want to keep the type names as defined in the Winglang Spec (so `Array`, `MutArray`, `Json`, `MutJson`, etc.) and actually fix the reference docs. See #2165 

We named `Array` as `ImmutableArray` due to a limitation on our jsii-docgen implementation, but as said we should find a way to fix it and the issue for it is #2165.

Closing this issue.
