### ISSUE TITLE
Completion: github co-pilot sometimes shadows completion

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#2864]
### I tried this:

See #2828, #2830, #2831, #2832.
This code for example doesn't autocompletes because copilot suggests code and it overrides wing lsp autocomplete behavior.
```ts
bring cloud;

let bucket = new cloud.Bucket();

bucket.
```
Notice I have added a blank line on line 4. If I remove it then autocomplete works as expected.

### This happened:

No autocomplete.

### I expected this:

To see autocomplete suggestions.

### Component

IDE Extension

### Wing Version

0.19.4

### Node.js Version

19.3.0

### Platform(s)

MacOS

### Anything else?

@MarkMcCulloh is checking whether it's possible that the vscode extension will add a setting to co-pilot to disable it for wing files. 

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by eladb** [comment]
I experimented with this a bit last week and I have some thoughts:

1. Co-pilot works and is useful for writing Wing code. I think disabling it is a shame.
2. This is the behavior co-pilot has in all languages. In rust, I find myself having to click ESC + "." many times due to the same issue.

I'd suggest deprioritizing this for now and seeing if this is something users also have concerns about.

Moving to P3.

**Comment by staycoolcall911** [comment]
We can close for now and see if this resurfaces at some point.
