### ISSUE TITLE
playground on the backend

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#3050]
Lets start with a POC with fly.io 

# already done
- analytics - what is the mechanism for having the console events reporting from the browser (or any other soluiton) 
- performance - loading time and interaction time 
# things to consider
- lifecycle - how and when are we terminating images
- spike resilience - 
  - Get higher quota
  - Load testing (curl) 
- cost - how much will it cost
- Known risks - DNS resolution for non-warmed up instance
- Reporting amount of instances
- Monitoring Price
- Configurable (feature flags?)
  - target browser - Edge, Safari, Firefox 
  - max instances
  - pre-warmed instance
- Latest version of wing
- Better uptime

**Comment by ekeren** [comment]
@ainvoner FYI

**Comment by skorfmann** [comment]
Just putting out my thoughts for the implementation:

- I would go with one app / machine per user
- Would try to host the vending machine on an edge network, e.g. Cloudflare or something similar, with the goal that the request to fly will be made from a location close to the user and therefore be routed to a close data center automatically
- Perhaps doing a request within the vending machine to the provisioned machine could warm it up already
- The image which is currently provisioned includes a [tired proxy](https://github.com/fly-apps/fastify-functions/blob/0f4ef94451f5298a999410f94405c4fb739df105/Dockerfile#L14), which will kill itself after x seconds. I think something like that could make sense in our case as well
- The fly.io forum was quite responsive, see here for more feedback from their side https://community.fly.io/t/machines-as-ephemeral-code-playground-backend/13735

**Comment by skorfmann** [comment]
That looks nice!

> see - https://playground-git-server-playground-monada.vercel.app/

So this is the frontend / UI app and also provisioning the backends? Is the code somewhere accessible?

>this warms up a few images which are always available, otherwise loading time is quite high. 

what means quite high? Have you tried other cpu / memory ratios?

> once a user interacts with the maching, it is self destructing after 15min.

cool!

**Comment by eladb** [comment]
Out of curiosity, what's the difference between the fly.io solution and a ECS/Fargate fleet? Is this about startup times? DNS? Edge?

**Comment by ShaiBer** [comment]
Moving Slack Convo here:
@ShaiBer - Does having pre-warmed images mean that costs are very high? Also, how fast do we warm up extra ones once some of the pre-warmed ones get taken

What happens if the machine self destructs after 15 mins and I then try to resume my session?

@ekeren - It depends on how many prewarm instance we need 

50 will be + $160 a month to our operating cost (regardless to usage)

We had about  +12 seconds loading time before we created the warn instances

The 15 minutes is a POC thing, it should rely on session connectivity. although I think we should have a hard limit to machine uptime 

If machine gets disconnected, we should show the proper pop up (similar to what happen when you logout)

@ShaiBer - $160 isn't too bad :) but how is it so cheap?

@ekeren - I think that the machines are weak, or we have a problem with the calculation 

@ShaiBer - And the logout is after 15 minutes from login, or 15 minutes of inactivity?

@ekeren - The 15 minutes is a POC thing, we haven’t discussed the session termination policy yet 

https://fly.io/docs/about/pricing/

https://community.fly.io/t/machines-as-ephemeral-code-playground-backend/13735/11

@ShaiBer - Do we have a quota for maximum number of machines?

@ShaiBer - About the cost, yes it's $160 per month if we are on shared CPUs. This can also explain the long load time as a shared CPU is shared between about 15 users.
It might be worth checking how much load time we'd get with a dedicated CPU.

About capacity, seems like 50k really frightens them, but I doubt we'll need it. 5k for launch day could be realistic though.

They did say that they assume gradual growth and we should talk to them if that's not the case. So I guess we should talk to them because we can have x1000 spike at launch day that would lift us from a micro account to a whale in an hour

But overall seems very promising and cost effective :muscle:

BTW, if we are stuck without extra machines to spin up, can we put more than one session on machine?

@eladb - Curious: what’s the primary difference between fly.io and a fleet of Fargate instances? Is that the direct url? 

@staycoolcall911 - Just wanted to say the load time is amazing :slightly_smiling_face: :muscle: :muscle:

**Comment by skorfmann** [comment]
> Out of curiosity, what's the difference between the fly.io solution and a ECS/Fargate fleet? Is this about startup times? DNS? Edge?

Simplicity. 

Not sure how the current implementation exactly works, but my original pitch was:

- cold startup time of a simple, minimal nodejs docker image in less than 5 seconds (it's using Firecracker under the hood)
- hence, stateless handling of the VMs (spin it up, let it shutdown after a while automatically)
- competitive pricing
- wouldn't call it edge, but at least being able to run vms in close proximity to the user
- fast time to market

**Comment by ekeren** [comment]
@eladcon we need to present a nice message if no more capacity is available

**Comment by ainvoner** [comment]
using web containers for safari and firefox as well.

**Comment by ainvoner** [comment]
need to decide if to move forward with this solution for unsupported browsers (safari 16.4<)

**Comment by ShaiBer** [comment]
> need to decide if to move forward with this solution for unsupported browsers (safari 16.4<)

I think we should

**Comment by skorfmann** [comment]
> need to decide if to move forward with this solution for unsupported browsers (safari 16.4<)

Beyond that, would be the option to include external nodejs scripts be interesting? My understanding is, that that's not possible on web containers, or am I wrong there?
