### ISSUE TITLE
improve monorepo tooling

### ISSUE THREAD

**Issue by skyrpex** [winglang/wing#3145]
The current setup is working but has some gotchas:
- Installs are slow since we don't use workspaces
  - Need to run `npm install` on the root after adding or removing packages to a subproject
- Need to add lots of code to add a new package
  - Same for publishing a new package
- There's no unified formatting and linting
- Mixed projen-based and projenless projects

I believe the suggestions below would improve our DX quite a lot:
- Use `pnpm` workspaces
  - Faster installs
  - Better caching
  - Better dependency management (no need to specify `file:../relative/path`: can use `@winglang/my-dependency`)
- Use `turbo` for tasks
  - No copious amounts of config
  - Remote caching
- Use Rollup/Esbuild based compilers, like `tsup`
  - bundles dev dependencies; leaves runtime dependencies as external
  - runs tsc for type checking
  - fast
- Become future proof:
  - Use ESM
  - Stop using enums (use types instead): TypeScript types will be valid in JavaScript (see [proposal](https://tc39.es/proposal-type-annotations/))
  - Specify the file extension in all imports (can use eslint rules to enforce and autofix)
- Use better `package.json` setup for TypeScript packages
  - `exports` field should point to `src/index.ts`
  - `publishConfig.exports` field should point to `dist/index.js`
  - This way, we don't need to build before TypeScript diagnostics are happy
- Become explicit about when to bundle third party dependencies or not
  - May save a lot of bundle size and runtime performance
- Use verdaccio for e2e tests with npm
  - This way, we can test the actual published packages
  - This will also allow us to test the `exports` field
- Custom projen project to enforce all of this?
  - Got a proof of concept of some projen projects for this. Can share later

**Comment by skyrpex** [comment]
Additionally, what do you think about this folder layout? Still uses apps, libs and tools but includes the package scope in the path. IMO it makes it really clear where the package belongs, and it's more consistent with the console, which has its own sets of apps and libs.

```
apps/
    @winglang/
        api-checker/
        jsii-docgen/
    vscode-winglang/
    wingconsole/
    winglang/
libs/
    @wingconsole/
        design-system/
        server/
        ui/
    @winglang/
        compiler/
        sdk/
        tree-sitter-wing/
        wingc/
        wingii/
tools/
    bump-pack/
    hangar/
```

**Comment by MarkMcCulloh** [comment]
Thanks Cristian, I put some thoughts below. I think I generally agree with most of what you said. Most of the difficulties with this repo is due to the nature of the rust/jsii-compat ts/ts, so most of the existing choices are not ideal. 
That being said, some of the existing techs are legitimately bad/lazy regardless of the complication 😅 

If I didn't mention something below, it means I agree with it assuming it doesn't break anything 😄 

---

> pnpm

Fully agree, as long as we can get past the issues with jsii. Also we need to make sure wing itself is compatible with pnpm-installed dependencies.

> turbo

Turbo is cool and would probably be better than nx. There are some slightly complicated relationships between projects due to the rust/wasm stuff. Nx should be able to do distributed caching too but these complications made it hard to get right IMO. Hopefully it will be easier in turbo. Alternatively, I've been following https://moonrepo.dev/ and it's really interesting.

> Stop using enums (use types instead): TypeScript types will be valid in JavaScript

This makes sense, although does this work with JSII?

> Custom projen project to enforce all of this

I love projen but frankly it is not great for monorepos. It's possible to make it work, of course, but it takes a lot of work. It basically becomes a whole other job to manage. When JSII is mixed with non-jsii, it's even worse. It's easier to bring standards up to the root and share them (especially for eslint/prettier/tsconfig/etc). I'd be open to seeing projen for all projects (except rust I guess?) but I'm not optimistic

> Use verdaccio for e2e tests with npm

We previously did this, but removed it due to the overhead. It was too slow so it got in people's way. I'm down to go back to it but we need to make sure the current method (symlink) is still an option IMO.

**Comment by MarkMcCulloh** [comment]
> From the experiments I did, the rust projects were all building correctly with wasm. It gets very simple if you think of them as npm packages that have a compile script and depend on each other.

Part of the complication is that the rust projects actually build in three ways:
- When running unit tests or running them directly, you're doing native builds. This is useful because it's fast and is properly debuggable
- When developing the repo locally building as wasm32-wasi, you're doing a debug build
- When you want to build for a release wasm32-wasi (slow), the wasm file is in a different place than the debug one

The first one doesn't really matter (except for caching, which means builds and tests technically have a different cache), but the other two even change the artifact location that is needed by the other project. As far as I can tell, turbo doesn't really handle the concept of a "release profile".
