### ISSUE TITLE
add open an issue to learn and playground

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#3293]
based on @Chriscbr [suggestion](https://winglang.slack.com/archives/G04G3TCHE12/p1688268216581589) we would like to give an option for the user to `report an issue`

Current play header:
![Image](https://user-images.githubusercontent.com/1727147/251456670-7959dd0c-4065-4154-af64-f005db0be8a1.png)

Current learn header:

![Image](https://user-images.githubusercontent.com/1727147/251456853-1daf532d-5fea-4565-ad69-2053daa7365b.png)

**Comment by eladb** [comment]
"report an issue" usually refers to reporting content violations (which is why this icon is not the right one).

I'd use something like "Submit an issue" or "Send Feedback" (probably "Send Feedback").
![Screenshot 2023-07-06 at 16 04 37](https://github.com/winglang/wing/assets/598796/ee5439b9-22e4-4e23-a7ff-cc32b2b80eb1)

**Comment by ainvoner** [comment]
in playground:
 - Icon at the action buttons section on the right (left most icon)
 - add code snippet
in learn 
 - Icon at the action buttons section on the right (left most icon) 
 - just open an issue

open in new tab
