### ISSUE TITLE
intercom stopped working in play/learn sites

### ISSUE THREAD

**Issue by ainvoner** [winglang/wing#3483]
### I tried this:

open learn/play sites and see the intercom widget

### This happened:

there is no intercom widget

### I expected this:

to have intercom :)

### Is there a workaround?

no

### Component

Playground

### Platform(s)

MacOS

### Anything else?

probably related to headers update in https://github.com/winglang/playground/commit/d00366e25d1ff4e43b6f0b2e886e80a03789fb74

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ekeren** [comment]
notice that it doesn't work for dynamic domains as well - e.g. https://9qb2ivlkj4.learn-ext.winglang.io/

**Comment by skyrpex** [comment]
The webcontainers only work in secure browser contexts. To enable secure contexts, the files we serve from our server must include a `Cross-Origin-Embedder-Policy=require-corp` or `Cross-Origin-Embedder-Policy=credentialless`. If `require-corp` is used, the page will only be able to load scripts, images and videos that return some specific headers. On the other hand, by using `credentiallesss`, we can still use scripts, images and videos securely.

We use `require-corp` and not `credentialless` because it's only implemented in Chromium-based browsers. Our analytics stack uses the segment cdn (and other cdns) to download the scripts, and they don't include the headers we need.

I thought that one solution would be to proxy the segment cdn, but we can't since there's multiple cdns and we don't have control over it. So it's a no go.

The only solution that comes to mind is to fine-tune each of the analytics solution we want to include. For example, adding Intercom manually and checking their cdn settings to see if we can either configure their HTTP headers, or self-host the intercom assets.

**Comment by skyrpex** [comment]
There's some info here:
- https://blog.stackblitz.com/posts/cross-browser-with-coop-coep/
- https://developer.stackblitz.com/platform/webcontainers/browser-support

**Comment by ainvoner** [comment]
@skyrpex if we will use the backend solution for all browsers that are not chrome, would it be possible to set the analytics properly for all?

**Comment by skyrpex** [comment]
Yeah. The backend solution doesn't require webcontainers nor these secure contexts.

**Comment by ekeren** [comment]
YIKES!

**Comment by ekeren** [comment]
@skyrpex, have you seen this? 
https://github.com/segmentio/analytics-next/issues/841

**Comment by ainvoner** [comment]
moving back to use fly.io backend for non chrome based browsers.
issue was resolved
