### ISSUE TITLE
Json: schema validation support fromJson for jsii imported structs

### ISSUE THREAD

**Issue by hasanaburayyan** [winglang/wing#3943]
Currently we can only call fromJson() on user defined structs, this is because we jsify user defined structs into Json schemas. However, we also treat interfaces imported through jsii as struct types, and since these are just imported from the stdlib we do not create jsified schemas.

Not super sure what the best approach to support this would be just yet.

support something like:
```js
bring cloud;

let j = { public: false };
let x = cloud.BucketProps.fromJson(j);
```

(broke this work out of https://github.com/winglang/wing/issues/3792 since its a separate issue)

**Comment by hasanaburayyan** [comment]
@staycoolcall911 I extracted this from 3792 since it orignally covered this and imported structs from other wing files. Not sure if this is as high priority as the work in [3792](https://github.com/winglang/wing/issues/3792)

**Comment by staycoolcall911** [comment]
Thanks @hasanaburayyan - I think it is high priority. I'll set it as p1, unless someone else has any interesting input on why it could/should be added later. @yoav-steinberg and @Chriscbr might be able to assist you with ideas how to impl

**Comment by Chriscbr** [comment]
I can try to suggest an implementation -- though it's just one approach, so feel free to take with a grain of salt. I think the solution can be split into two parts: type checking and jsification.

For type checking, we'd need to make sure `fromJson` and `schema` is modeled in the type system as available methods on every json-safe struct (regardless of where it came from). This might already work - I haven't checked.

For jsification, we could try changing how we're emitting struct files into a lazy process, so instead of eagerly emitting a `.struct.js` file for each `Struct` statement, we only emit a `.struct.js` file the first time we encounter a `Reference` expression that refers to a given struct (or a `Call` expression to `fromJson` / `schema`).

**Comment by hasanaburayyan** [comment]
@Chriscbr thanks for the feedback,

> For type checking, we'd need to make sure fromJson and schema is modeled in the type system as available methods on every json-safe struct (regardless of where it came from). This might already work - I haven't checked.

Yes this already works.

As for emitting a struct definition when we encounter a reference expression, let me look into that. It sounds logical that I should just be able to do a lookup on the struct and get everything I need for emitting the schema, though I guess that also means I need to jsify the reference to reference the schema file definition rather than the actual imported reference (maybe).
