### ISSUE TITLE
`QueueProps.retentionPeriod` doesn't work  for target `sim`

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#4233]
### I tried this:

```
bring cloud;
bring util;

let q = new cloud.Queue(cloud.QueueProps{retentionPeriod: 5s});

test "retentionPeriod" {
  q.push("hello");
  q.push("world");
  
  util.sleep(10s);

  assert(util.waitUntil((): bool => {
    return q.approxSize() == 2;
  }));
}
```

### This happened:

Test passed.

### I expected this:

I expected test to fail.

### Component

SDK

### Wing Version

0.31.12

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by staycoolcall911** [comment]
This should be relatively easy to tackle for new contributors.

To see the relevant code check here:
1. https://github.com/winglang/wing/blob/main/libs/wingsdk/src/target-sim/queue.ts
2. https://github.com/winglang/wing/blob/main/libs/wingsdk/src/target-sim/queue.inflight.ts

Please note:
- The code above should have failed compilation, since the default `timeout` is 10s and the `retentionPeriod` must be greater or equal to the `timeout`.
- We need to add a couple of tests for `retentionPeriod` in https://github.com/winglang/wing/blob/main/examples/tests/sdk_tests/queue

**Comment by gcfbn** [comment]
Fixed in the https://github.com/winglang/wing/pull/4273

**Comment by staycoolcall911** [comment]
Great, thank you @gcfbn 🙏
