### ISSUE TITLE
Flaky Wing Console

### ISSUE THREAD

**Issue by garysassano** [winglang/wing#4468]
### foo.main.w
```
bring cloud;

let bucket = new cloud.Bucket() as "bucket1";
let bucket2 = new cloud.Bucket() as "bucket2";

let f1 = inflight () => {
    bucket.put("hello.txt", "Hello, sync!");
};
let f2 = inflight () => {
    f1.invokeAsync("");
};

new cloud.Function(f1) as "f1";
new cloud.Function(f2) as "f2";
```

`mywing it foo.main.w`

### bar.main.w

```
bring cloud;

let f1 = new cloud.Function(inflight (input: str): void => {
  log("log inside f1");
}) as "f1";

let f2 = new cloud.Function(inflight (input: str): void => {
  f1.invokeAsync("");
}) as "f2";
```

`mywing it bar.main.w`

### This happened:

![flaky-console-1](https://github.com/winglang/wing/assets/10464497/c9eab46e-4b53-40b7-9cc8-749c842a4486)
![flaky-console-2](https://github.com/winglang/wing/assets/10464497/59f862ca-5580-4654-9a25-86ff8aafcc43)

### I expected this:

I expected either both snippets to fail or both snippets to succeed.

### Component

Wing Console

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skyrpex** [comment]
I got compiler error on both examples in Wing 0.36.1. What version are you using?

**Comment by garysassano** [comment]
@skyrpex Forgot to mention that you need to use my branch [garysassano/lambda-invoke-async](https://github.com/winglang/wing/tree/garysassano/lambda-invoke-async)

**Comment by MarkMcCulloh** [comment]
[See here for a combination of both examples using `invoke` instead](https://www.winglang.io/play/?code=YgByAGkAbgBnACAAYwBsAG8AdQBkADsACgAKAGwAZQB0ACAAcgBhAHcASQBuAGYAbABpAGcAaAB0ACAAPQAgAGkAbgBmAGwAaQBnAGgAdAAgACgAKQA6ACAAdgBvAGkAZAAgAD0APgAgAHsACgAgACAAbABvAGcAKAAiAGwAbwBnACAAaQBuAHMAaQBkAGUAIABmADEAIgApADsACgB9ADsACgBsAGUAdAAgAGYAMQAgAD0AIABuAGUAdwAgAGMAbABvAHUAZAAuAEYAdQBuAGMAdABpAG8AbgAoAHIAYQB3AEkAbgBmAGwAaQBnAGgAdAApACAAYQBzACAAIgBmADEAIgA7AAoACgBsAGUAdAAgAGYAMgAgAD0AIABuAGUAdwAgAGMAbABvAHUAZAAuAEYAdQBuAGMAdABpAG8AbgAoAGkAbgBmAGwAaQBnAGgAdAAgACgAKQA6ACAAdgBvAGkAZAAgAD0APgAgAHsACgAgACAALwAvACAAdABoAGkAcwAgAHcAbwByAGsAcwAgAGIAZQBjAGEAdQBzAGUAIABmADEAIABpAHMAIABjAGwAbwB1AGQALgBGAHUAbgBjAHQAaQBvAG4ACgAgACAAZgAxAC4AaQBuAHYAbwBrAGUAKAAiACIAKQA7AAoACgAgACAALwAvACAAdABoAGkAcwAgAGQAbwBlAHMAIABuAG8AdAAgAHcAbwByAGsAIABiAGUAYwBhAHUAcwBlACAAcgBhAHcASQBuAGYAbABpAGcAaAB0ACAAaQBzACAAagB1AHMAdAAgAGEAbgAgAGkAbgBmAGwAaQBnAGgAdAAKACAAIAByAGEAdwBJAG4AZgBsAGkAZwBoAHQALgBpAG4AdgBvAGsAZQAoACIAIgApADsACgAKACAAIAAvAC8AIAB0AGgAaQBzACAAdwBvAHIAawBzACAAYgBlAGMAYQB1AHMAZQAgAHIAYQB3AEkAbgBmAGwAaQBnAGgAdAAgAGkAcwAgAGoAdQBzAHQAIABhAG4AIABpAG4AZgBsAGkAZwBoAHQACgAgACAAcgBhAHcASQBuAGYAbABpAGcAaAB0ACgAKQA7AAoAfQApACAAYQBzACAAIgBmADIAIgA7AA%3D%3D)

`invoke` (and `invokeAsync` in your branch) are methods on cloud.Function rather than inflights themselves. Invoking a plain inflight from another inflight just needs to use `()` to call it. So this is working as intended
