### ISSUE TITLE
Stateful simulator

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#5038]
The high level requirement here is to add a mechanism to the simulator that allows it to keep state (e.g. DB data), to support production-like experience.

**Comment by Chriscbr** [comment]
Design sketch:

- High level solution: use a state file.
- A state file is saved to disk when the simulator is stopped, and every 5 seconds (configurable).
    - Each resource has a "save" method that, when called, should return a JSON snapshot of that resource's state. The save function is called with the path of a directory where additional files can be stored (for example objects in a bucket), and referenced by the main state file.
    - If the "save" method doesn't exist or throws an error, no state is saved.
- When the simulator is started with a state file, then information about a resource's previous state will be given to the resource's "init" method
    - If the resource was newly added (and it has no corresponding state in the state file), it will be initialized with empty/default state
    - If there is state for a resource no longer present in the app, it will be discarded.
- Where is state information stored?
    - Option 1: store it in `target/` folder (next to simulator.json etc.). (recommended)
    - Option 2: store it in ~/.wing/state/.
- Examples of state info saved for each resource:
    - Bucket / Website: a list of all files and paths to them on the user's file system
    - Counter: the number value
    - Queue: the list of messages and each message's remaining time
    - Function, Topic, OnDeploy, Service, Api, Secret, Schedule: no state
    - sim.State: the value (must be serializable)
- Future design ideas:
    - For Wing Console to work for both sim and production apps, we need a generic "runApp" function that works for all targets.
    - Instead of using "save" methods, consider modeling all simulator all state through a set of primitives, like `sim.State`. Inflight methods like bucket.put or counter.inc will dispatch to methods on `sim.State`, which will have simulation-specific behavior.

**Comment by eladb** [comment]
A few thoughts:

I think we might need a more low level mechanism in order to support things like state of containers (think redis).

Perhaps instead of a state file, we can allocate a state *directory*, and a subdirectory for each resource. Then, pass it into the `save(dir)` and `load(dir)` and also expose it to the resource through the `ISimulatorContext`.

When a `Simulator` is created, it should be possible to provide a base directory for the state, and this how we can put the state in a persistent container volume when deployed on the cloud.

I am wondering if we can need to or should separate `load()` and `init()`. Being able to load state into a running resource could be hairy but doing that during initialization should be much easier. And I don't see a real use case for explicitly loading state (only saving).

**Comment by Chriscbr** [comment]
agree, I think a directory makes the most sense.

state of containers is a good callout. I did a cursory google search and it looks like there are ways to snapshot container state etc. one concern might be if saving state of some resources takes a long time (would we need to pause the simulation in order to save the state?) but let's see how far we get

**Comment by eladb** [comment]
I don't think we will need to store the state of the container but rather just mount a volume into the container so the server that runs inside can store state.

For example, a Postgres server will be configured to store its state in the mounted volume which will map into the simulator state directory.

I am also not sure we really need to store state periodically, just before we stop the app and migrate it to the new container. (Will cause disruption of course but that's a reasonable constraint for cloudlets)

**Comment by eladb** [comment]
Additional requirements to consider:

1. Keeping a container alive in case the image hasn't changed.
1. Keep a listener's port the same across updates

To support this we might need to enrich the lifecycle model for simulator resources to be more like cloud resources (create/update/delete) so that a resource can make a decision about how to update itself.

**Comment by Chriscbr** [comment]
> Keeping a container alive in case the image hasn't changed.

Can you elaborate on this detail/concept? My initial thinking was to keep all state between simulation runs in the state directory/file. Intuitively, this means you can save your state somewhere, spin up a new machine, load any state files on to it, and start the simulator (handing a path to the state directory) and get back to your previous execution state - or as close as practically possible :-). The upside of this is we wouldn't take any assumptions on whether simulation runs are being executed on the same machine or not.

Would keeping a container alive be an optimization of sorts? I'm curious (based on my limited understanding of containers) if restarting a container with the same storage is always guaranteed to take us back to the same execution state as if we had just kept the container running.

**Comment by eladb** [comment]
> Would keeping a container alive be an optimization of sorts?

Yes, it is an optimization for local development, which I think we should take into account when we are designing this solution.

**Comment by Chriscbr** [comment]
Completed in #5164
