### ISSUE TITLE
cant lift objects from a custom platform

### ISSUE THREAD

**Issue by eladcon** [winglang/wing#5836]
### I tried this:

write a custom platform for the awscdk target
```js
// my-custom-platform/index.js
// this folder also has a package.json with @winglang/platform-awscdk as a dependency
const { Function } = require("@winglang/platform-awscdk/lib/function.js");
const {FUNCTION_FQN} = require("@winglang/sdk/lib/cloud");
module.exports.Platform = class Platform {
  newInstance(type,scope,id,props) {
    if (type === FUNCTION_FQN) {
      return new Function(scope, id, props);
    }
  }
}
```

compile a wing app with both platforms
`CDK_STACK_NAME=test wing compile -t @winglang/platform-awscdk -t ../my-custom-platform/index.js main.w`

```wing
// main.w
// this folder also has a package.json with @winglang/platform-awscdk as a dependency
bring cloud;

let b = new cloud.Bucket();

new cloud.Function(inflight () => {
  b.get("a");
});
```

### This happened:

```
Error: buckets can only be bound by tfaws.Function for now
```

(the `tfaws.Function` is just a typo)

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
This error shouldn't be raised anymore since we've now defined a more general purpose "isAwsInflightHost" function -- see the check here: https://github.com/winglang/wing/blob/9adaea0116fc8d00229d45660b6fdf1456708ec8/packages/%40winglang/sdk/src/target-tf-aws/function.ts#L309-L311

and the implementation here:

https://github.com/winglang/wing/blob/9adaea0116fc8d00229d45660b6fdf1456708ec8/packages/%40winglang/sdk/src/shared-aws/inflight-host.ts#L11

I've opened a separate issue for making sure we add this API for all of the major cloud targets: https://github.com/winglang/wing/issues/7081
