### ISSUE TITLE
Increase coverage using automatic cloud snapshot tests

### ISSUE THREAD

**Issue by eladb** [winglang/wing#5958]
I'd like to be able to capture a snapshot of the output when compiling to cloud targets and use it to protect against regressions in CI (without having to deploy to the cloud).

### RFC

See https://github.com/winglang/wing/pull/6044

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

**Comment by Chriscbr** [comment]
I think high level user story makes sense, I'm only unsure about the choice to to automatically take snapshots of every test the user writes. By default, Wing's syntax encourages you to reuse the same test fixtures or preflight components for multiple tests so that you don't have to write the same things over and over. So in the code below, the three tests would all produce identical snapshots, which is not great.

```js
let bucket = new cloud.Bucket();
let api = new cloud.Api();
let dynamodb = new dynamodb.Table();

test "scenario 1" {
  // ...
}

test "scenario 2" {
  // ...
}

test "scenario 3" {
  // ...
}
```

**Comment by eladb** [comment]
> So in the code below, the three tests would all produce identical snapshots, which is not great.

I think a single `.test.w` file should product a single snapshot, not one per test.

**Comment by Chriscbr** [comment]
@eladb Can this be closed per https://github.com/winglang/wing/pull/6163 ?

**Comment by eladb** [comment]
Yes, we still need to run this in winglibs, but that's a different issue.
