### ISSUE TITLE
confusing map view, putJson appears with no apparent reason

### ISSUE THREAD

**Issue by ekeren** [winglang/wing#6486]
### I tried this:

```wing
bring cloud;

let b = new cloud.Bucket();
let sqs = new cloud.Queue();
b.onCreate(inflight (f) => {
  sqs.push(f);
});

sqs.setConsumer(inflight (m) => {
  log("{m}");
});

let fn = new cloud.Function(inflight () => {
  b.put("file.txt", "Hello World");
});
```

### This happened:

![image](https://github.com/winglang/wing/assets/1727147/75e1be51-dd63-49a8-a572-2ea405779f25)

### I expected this:

1.  Not to see `putJson`
2.  The oncreate handler should have a connection to the queue (via push) - (probably already covered by https://github.com/winglang/wing/issues/6458) 

### Wing Version

0.73.46

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by Chriscbr** [comment]
> The oncreate handler should have a connection to the queue (via push) - (probably already covered by https://github.com/winglang/wing/issues/6458)

I believe this will be fixed by #6509

> Not to see putJson

I want to say this could be expected behavior, but I'm curious to learn what you'd like to see as a user.

Take this example:

```js
bring cloud;

let b = new cloud.Bucket();
let q = new cloud.Queue();
q.setConsumer(inflight () => {
  b.put("file.txt", "Hello World");
});
```

I never call the queue's "push" method in the app code. But the Wing Console shows "push()" in the map.

<img width="623" alt="Screenshot 2024-05-17 at 12 00 49 AM" src="https://github.com/winglang/wing/assets/5008987/4ab538e1-0a88-4923-870d-52283bb0c11e">

@ekeren I'm curious does this feel like the same problem to you? Or do you think the problem showing `put()` and `putJson()` is different?

(BTW, we could hide the inner function if needed so that it instead looks like the map below)
<img width="321" alt="Screenshot 2024-05-17 at 12 14 10 AM" src="https://github.com/winglang/wing/assets/5008987/3a5fdfe2-ed71-439d-b6a6-7fd0894d1ba2">

**Comment by ekeren** [comment]
I don't understand why `push` is there, it is very confusing 

I would expect to see a:
> ⚡️ consumer 
Handler and no `push`

**Comment by Chriscbr** [comment]
@ekeren I'm not sure I understand but maybe a synchronous discussion will help. 😄 

BTW, I want to share one more example where I created my own Queue class:

```js
bring cloud;

class Queue {
  b: cloud.Bucket;
  new() {
    this.b = new cloud.Bucket();
    nodeof(this.b).hidden = true;
  }
  pub inflight push(msg: str) {
    this.b.put("file.txt", msg);
  }
  pub inflight pop() {
    this.b.delete("file.txt");
  }
  pub inflight boring() {
    log("this method does not interact with other resources");
  }
  pub setConsumer(fn: inflight (str): void) {
    this.b.onUpdate(fn);
  }
}

let b = new cloud.Bucket();
let q = new Queue();
q.setConsumer(inflight () => {
  b.list();
});
```

The `Queue` class has three inflight methods, `push`, `pop`, and `boring`. `boring` does not interact with any other resources.

Even though I do not have a `cloud.Function` that is calling the `push` or `pop` methods on my class, to me it feels intuitive that the visual map shows the methods of the class I wrote.

<img width="389" alt="Screenshot 2024-05-17 at 2 13 21 PM" src="https://github.com/winglang/wing/assets/5008987/e2654ce6-326d-4350-baf1-e12729526061">

To me what may be confusing is not all of my class's methods are shown - the Wing Console doesn't show there is a `boring` method that can also be called.

**Comment by skyrpex** [comment]
I'd prefer to have the public API of every class, too. The private methods, not that important IMO.
