### ISSUE TITLE
API for creating Wing clients in other languages

### ISSUE THREAD

**Issue by Chriscbr** [winglang/wing#6538]
### Use Case

The use case is for providing a seamless development experience for teams where application developers and platform engineers have separate responsibilities, and where application developers aren't dealing with Wing or infrastructure.

As a platform engineer I'd like to use Wing to create the preflight infrastructure for developers in my organization, and then produce client libraries in TypeScript (or other languages) for accessing that infrastructure within other pieces of code. Imagine for example that the application developers write TypeScript or Python running in containers in their own repo, and that repo's code is already being automatically deployed with GitOps via ArgoCD or other means.

As an application developer I'd like to consume the TypeScript package published by the platform team and write application code that interacts with these resources (using whichever methods or permissions have been granted by the platform team). If I'm running my TypeScript code / container locally I expect the Wing clients to connect to the Wing simulator and interact with the simulated resources, and when my code is deployed to the AWS I expect the clients to connect to the real cloud resources

_(credit goes to @eladb for raising this use case)_

### Proposed Solution

On the platform engineer side, I can write a Wing application that looks something like this:

```js
bring cloud;
bring std;

let b = new cloud.Bucket();

let client = new std.TypeScriptClient();
client.lift(b, as: "myBucket", with: ["put"]);

new TerraformOutput(name: "WingClientContext", client.context);
```

TypeScriptClient will produce a JavaScript npm package with TypeScript typings for the client (with package.json, index.ts, index.d.ts etc.). By exporting the client context through Terraform output, I can expose the deploy-time configuration needed by the Wing Client. As a platform engineer I can then mount that configuration to the containers through a ConfigMap or other means.

On the application developer side, I can use the Wing client with `npm i @acme/wing-clients` and using it like so:

```js
import { createClient } from "@acme/wing-clients";

async function main() {
  const client = await createClient(); // reads from process.env.WING_CLIENT_CONTEXT
  await client.myBucket.put("key", "value");
}
```

In this simple example, only myBucket (a class from the Wing SDK) is being exposed, but it's possible to package user-defined classes / abstractions as well.

### Component

Compiler, SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Discord](https://t.winglang.io/discord).

**Comment by eladb** [comment]
I would constraint this design to TypeScript for now. Supporting other languages is a bigger project and I think it will be valuable to take it piece by piece.

**Comment by ekeren** [comment]
Nice!

re:
```js 
 client.lift(b, as: "myBucket", with: ["put"]);
```
In my mind I associate lifting to also granting permission on a Host, it seems that this issue is not connected to any permissions granting (unless I am mistaken) 
 
Shouldn't this be:
```js 
 client.add(b, as: "myBucket", with: ["put"]);
```

**Comment by eladb** [comment]
When compiled to AWS, it should also be possible to get the IAM policy required in order to allow the client to be used, so I think using the term "lift" here makes sense.

I am not sure exactly how these permissions are going to be outputted (maybe another Terraform output) but there should be a way to obtain them if desired.

**Comment by MarkMcCulloh** [comment]
> Imagine for example that the application developers write TypeScript or Python running in containers in their own repo, and that repo's code is already being automatically deployed with GitOps via ArgoCD or other means.

I'm curious about the desired dev workflow here. Where is the infrastructure required by the ts or python defined? Is the intention that it's all centralized the ts is just expecting it to be there? Is there going to be some wing code next to the ts? Is it expected to run wing as part of the local dev for ts?

I feel like there will have to be some defined relationship between wing and code consuming the client to support useful dev workflows.

**Comment by eladb** [comment]
@MarkMcCulloh great points. Which definitely need hashing out.

As an exercise, let's assume that the app code is managed in a *separate repository* from the infrastructure code and that the infra is always deployed *before* the app so that when the app is deployed it can rely on the fact that the infra is there (that's the common approach as far as I am seeing).

I think it's reasonable to require that part of the infra release workflow, some sort of "wing client" is created and published either to an organizational package manager (like artifactory) or maybe committed to the application repository.

The second thing to think about is how would the client have the relevant context information (like ARNs, connection strings, URLs) in order to be able to connect to the deployed infrastructure. In many cases this context information is only available after a resource is deployed.

If the client is published to the package repository during build (which is the common model) then we will need some kind of late binding during deployment or runtime. For example, we could write a ConfigMap to the K8S cluster that will be mounted to the application pods and used by the client during initialization.

Alternatively, if we generate and publish the client to the package repository *during deployment*, then we can possibly bake in all this context information and the client becomes self-contained.

I suggest we write an RFC that proposes an end-to-end solution and have the discussion there.
